#spring.application.name=fourthlecture

server:
  port: 8080

spring:
  application:
    name: gateway-eureka-app

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/